### ISSUE TITLE
New form users should be customers not subscribers

### ISSUE THREAD

**Issue by Hitman007** [Hitman007/CRG-ArcticColdCapsMods#10]
Unexplained bug only showing up on production

**Comment by Hitman007** [comment]
write a function that turns all users with the role 'subscriber' and make them a 'customer', and make any 'shop manager' a nurse. Put it somewhere.

**Comment by CRG-Freelance1** [comment]
Just a clarification, Editor role will still be present or they will be replaced by the Nurse role?

**Comment by Hitman007** [comment]
Ack. I meant SHOP MANAGER.
SHOP MANAGER should turn into Nurse
SUBSCRIBER should turn into Customer

**Comment by CRG-Freelance1** [comment]
I have made Shop Manager to a Nurse. Only question is, on the plugin, how is the "Customer" role created? I would need to know before making changes because this might affect DB. Thanks.

**Comment by Hitman007** [comment]
Customers are the main role assigned by Woocommerce for product buyers. If a user creates an account by purchasing something, they become a customer. https://docs.woothemes.com/document/roles-capabilities/

**Comment by CRG-Freelance1** [comment]
I see. So it is generated by WooCommerce. I am not sure how to approach this. Because if I set Subscriber to Customer, then there will be 2 Customer roles available. Should I remove "Subscriber" role entirely? Can you give me an idea what the best approach should be?
