### ISSUE TITLE
Modify dashboard

### ISSUE THREAD

**Issue by Hitman007** [Hitman007/CRG-ArcticColdCapsMods#11]
We're going to add our own admin widget.
See: https://youtu.be/1jWqxjIeCKM

notes:
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=wordpress+remove+admin+widgets

**Comment by CRG-Freelance1** [comment]
Done. I will close this issue now. Please reopen if needed. Thanks.
