### ISSUE TITLE
Do something when a user orders a product

### ISSUE THREAD

**Issue by Hitman007** [Hitman007/CRG-ArcticColdCapsMods#14]
Just like the info sheet link we put in the users menu on the dashboard, we are going to do something similiar.For those users that have actually ordered a particular product, by product ID, we're going to add some functionality to the users admin menu. We need a small form for some inputs for those users to appear. This should appear in the users admin area, similiar to what you did before. However, you can do it anyway that works, wordpress filters, jquery, whatever:

Checkbox - name:recurring-true
If above checked:
     text:name:chemo-rounds-remaining (use jquery to hide/show)
     text:name: next-billing-date
     hidden:name:recurring-user-id
     submit:value='Update'

Put data into user_meta. 
Look up data to populate fields for users who have the data

**Comment by Hitman007** [comment]
https://sozot.com/how-to-hook-into-woocommerce-to-trigger-something-after-an-order-is-placed/

**Comment by Hitman007** [comment]
This is for on the production server, when they order the 'basic rental', we're going to put in a manual recurring charge feature. But the product ids are different, becaise i stupidly unlinked the databases. Oh well. Anyway, we want this mini form to appear once a person has ordered product(x) one time. You can even use a user meta data boolean to flag which users get the mini form.

**Comment by Hitman007** [comment]
Actually, do it this way: we'll assign a boolean true or false 'has-recurring' for users who have ordered the product, and we'll show the form or not baed on that. So for now, just pick a user and give themthe dummy flag, and show the form based on that. We'll figure out HOW to set the flag later.

**Comment by Hitman007** [comment]
Note Wordpress can't store booleans in user_meta, we'll use actual strings 'TRUE' or 'FALSE'. Well, I guess only TRUE or not there.

**Comment by CRG-Freelance1** [comment]
Makes sense. One thing confuses me though. the form you mentioned will be visible on every individual user profile? or just another custom column on the user area?

**Comment by Hitman007** [comment]
just a custom column, you can put the checkbox for every user. In the info sheet, you did a logical check to see if the link should appear or not. On this one, just put a column and a checkbox for every user, no check required.

**Comment by CRG-Freelance1** [comment]
There will be a form when the checkbox is clicked right? Can I put a button instead to show a modal? (I said lightbox earlier, lol)
