### ISSUE TITLE
Required forms

### ISSUE THREAD

**Issue by Hitman007** [Hitman007/CRG-ArcticColdCapsMods#9]
Put these MSWord docs as html in a Wordpress page. Make them look at least semi-good. https://github.com/Hitman007/CRG-ArcticColdCapsMods/tree/master/word-forms

**Comment by CRG-Freelance1** [comment]
I have created the Wordpress pages for the 2 forms:
http://customrayguns.net/artic-cold-caps-hipaa-authorization-form/
http://customrayguns.net/terms-and-conditions/

I am not sure if I should make some parts editable. Let me know if this is all static and I will edit. Thanks
